### ISSUE TITLE
Hi,I need a help

### ISSUE THREAD

**Issue by Harl123** [MattyAB/BlockExplorer#1]
Could you show your 
C:\Users\matth\onedrive\documents\visual studio 2017\Projects\BlockExplorer\BlockExplorer\PassStore.xml
xml file?
We need it :+1:

**Comment by MattyAB** [comment]
Sorry, I'm on business until Friday, but should be able to get it to you then. It's on my ToDo to add this to the readme, but if you look in program.cs, you should be able to work out the format of it.

**Comment by MattyAB** [comment]
Here is my PassStore.xml: [https://pastebin.com/unP0baY6](https://pastebin.com/unP0baY6)

**Comment by Harl123** [comment]
thanks a lot

**Comment by MattyAB** [comment]
No problem, let me know how you get on 👍

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
