### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by mathis1337** [MattyAB/BlockExplorer#2]
There are no instructions to go with this. Don't suppose they exist anywhere do they? Also a bunch of reference files are missing causing it to not compile.

**Comment by MattyAB** [comment]
Nope, sorry. This is very unfinished and so there are no instructions, and it doesn't really do much that you would be interested in. At the moment, all it does is load current blocks from a bitcoin node instance into a MySql server instance; not particularly noteworthy.
